/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SefariaLinkerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/expansions.ts
var DP = `(?:''|[""\u05F4])`;
var SHORTFORM_EXPANSIONS = [
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 1 — SHULCHAN ARUKH WITH SECTION + SIMAN (most specific first)
  // ════════════════════════════════════════════════════════════════════════════
  // Sh''A O"C 123.4  →  Shulchan Arukh, Orach Chayim 123:4
  { pattern: new RegExp(`\\bSh${DP}A\\s+O${DP}C\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Shulchan Arukh, Orach Chayim $1:$2" },
  // Sh''A Y"D 123.4
  { pattern: new RegExp(`\\bSh${DP}A\\s+Y${DP}D\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Shulchan Arukh, Yoreh De'ah $1:$2" },
  // Sh''A E"H 123.4
  { pattern: new RegExp(`\\bSh${DP}A\\s+E${DP}H\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Shulchan Arukh, Even HaEzer $1:$2" },
  // Sh''A C"M 123.4
  { pattern: new RegExp(`\\bSh${DP}A\\s+C${DP}M\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Shulchan Arukh, Choshen Mishpat $1:$2" },
  // Sh''A 123.4  (bare — default to Yoreh De'ah, most common in halacha notes)
  { pattern: new RegExp(`\\bSh${DP}A\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Shulchan Arukh, Yoreh De'ah $1:$2" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 2 — SHULCHAN ARUKH COMMENTARIES (with siman.seif)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bShach\s+(\d+)\.(\d+)/g, replacement: "Siftei Kohen on Shulchan Arukh, Yoreh De'ah $1:$2" },
  { pattern: /\bTaz\s+(\d+)\.(\d+)/g, replacement: "Turei Zahav on Shulchan Arukh, Yoreh De'ah $1:$2" },
  { pattern: new RegExp(`\\bB${DP}H\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Ba'er Hetev on Shulchan Arukh, Yoreh De'ah $1:$2" },
  { pattern: new RegExp(`\\bN${DP}HaK\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Nekudot HaKesef on Shulchan Arukh, Yoreh De'ah $1:$2" },
  { pattern: new RegExp(`\\bP${DP}T\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Pischei Teshuva on Shulchan Arukh, Yoreh De'ah $1:$2" },
  { pattern: new RegExp(`\\bB${DP}Y\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Beit Yosef, Yoreh De'ah $1:$2" },
  { pattern: new RegExp(`\\bD${DP}M\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Darkei Moshe, Yoreh De'ah $1:$2" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 3 — TUR (with siman.seif)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bTur\s+(\d+)\.(\d+)/g, replacement: "Tur, Yoreh De'ah $1:$2" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 4 — RAMBAM / MISHNEH TORAH (section abbreviations with chapter.halacha)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: new RegExp(`\\bM${DP}A\\s+(\\d+)\\.(\\d+)`, "g"), replacement: "Mishneh Torah, Forbidden Foods $1:$2" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 5 — STANDALONE RISHON / ACHARON WORKS
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bIVHA\b/g, replacement: "Issur VeHeter HaArokh" },
  { pattern: /\bSmak\b/g, replacement: "Sefer Mitzvot Katan" },
  { pattern: /\bSmag\b/g, replacement: "Sefer Mitzvot Gadol" },
  // D"H / DH / "dibur hamaschil" — strip the marker and all words following it
  // up to (but not including) the next preposition that introduces the citation.
  // Greedy negative-lookahead: consume words as long as they are NOT in/on/at/al.
  { pattern: new RegExp(`\\bD${DP}H(?:\\s+(?!(?:in|on|at|al)\\b)\\S+)+`, "g"), replacement: "" },
  { pattern: /\bDH(?:\s+(?!(?:in|on|at|al)\b)\S+)+/g, replacement: "" },
  { pattern: /\bdibur\s+hamaschil(?:\s+(?!(?:in|on|at|al)\b)\S+)*/gi, replacement: "" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 6 — TALMUD TRACTATE ABBREVIATIONS (gershayim-style)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: new RegExp(`\\bA${DP}Z\\b`, "g"), replacement: "Avodah Zarah" },
  { pattern: new RegExp(`\\bB${DP}K\\b`, "g"), replacement: "Bava Kamma" },
  { pattern: new RegExp(`\\bB${DP}M\\b`, "g"), replacement: "Bava Metzia" },
  { pattern: new RegExp(`\\bB${DP}B\\b`, "g"), replacement: "Bava Batra" },
  { pattern: new RegExp(`\\bY${DP}T\\b`, "g"), replacement: "Beitzah" },
  { pattern: new RegExp(`\\bR${DP}H\\b`, "g"), replacement: "Rosh Hashanah" },
  { pattern: new RegExp(`\\bM${DP}K\\b`, "g"), replacement: "Moed Katan" },
  { pattern: new RegExp(`\\bK${DP}H\\b`, "g"), replacement: "Kiddushin" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 8 — TANAKH: TORAH (Hebrew/Ashkenazi → English canonical)
  // More specific compound forms first, then single-word forms.
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bBereishis\b/g, replacement: "Genesis" },
  { pattern: /\bBereishit\b/g, replacement: "Genesis" },
  { pattern: /\bBereshit\b/g, replacement: "Genesis" },
  { pattern: /\bShemos\b/g, replacement: "Exodus" },
  { pattern: /\bShemot\b/g, replacement: "Exodus" },
  { pattern: /\bShmot\b/g, replacement: "Exodus" },
  { pattern: /\bVayikra\b/g, replacement: "Leviticus" },
  { pattern: /\bWayikra\b/g, replacement: "Leviticus" },
  { pattern: /\bBamidbar\b/g, replacement: "Numbers" },
  { pattern: /\bBemidbar\b/g, replacement: "Numbers" },
  { pattern: /\bDevarim\b/g, replacement: "Deuteronomy" },
  { pattern: /\bDevorim\b/g, replacement: "Deuteronomy" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 9 — TANAKH: NEVI'IM (Prophets)
  // Compound "I/II" forms before plain name to avoid partial matches.
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bYehoshua\b/g, replacement: "Joshua" },
  { pattern: /\bShoftim\b/g, replacement: "Judges" },
  // Samuel — I/II prefixed forms first
  { pattern: /\bI\s+Shmuel\b/g, replacement: "I Samuel" },
  { pattern: /\bII\s+Shmuel\b/g, replacement: "II Samuel" },
  { pattern: /\bShmuel\s+Aleph\b/gi, replacement: "I Samuel" },
  { pattern: /\bShmuel\s+Beis\b/gi, replacement: "II Samuel" },
  { pattern: /\bShmuel\s+Bet\b/gi, replacement: "II Samuel" },
  // Kings — I/II prefixed forms first
  { pattern: /\bI\s+Melachim\b/g, replacement: "I Kings" },
  { pattern: /\bII\s+Melachim\b/g, replacement: "II Kings" },
  { pattern: /\bMelachim\s+Aleph\b/gi, replacement: "I Kings" },
  { pattern: /\bMelachim\s+Beis\b/gi, replacement: "II Kings" },
  { pattern: /\bMelachim\s+Bet\b/gi, replacement: "II Kings" },
  // Chronicles
  { pattern: /\bI\s+Divrei\s+Hayamim\b/g, replacement: "I Chronicles" },
  { pattern: /\bII\s+Divrei\s+Hayamim\b/g, replacement: "II Chronicles" },
  { pattern: /\bDivrei\s+Hayamim\s+Aleph\b/gi, replacement: "I Chronicles" },
  { pattern: /\bDivrei\s+Hayamim\s+Beis\b/gi, replacement: "II Chronicles" },
  { pattern: /\bDivrei\s+Hayamim\s+Bet\b/gi, replacement: "II Chronicles" },
  // Latter Prophets (Yeshayahu etc.)
  { pattern: /\bYeshayahu\b/g, replacement: "Isaiah" },
  { pattern: /\bYeshaya\b/g, replacement: "Isaiah" },
  { pattern: /\bYirmiyahu\b/g, replacement: "Jeremiah" },
  { pattern: /\bYirmiya\b/g, replacement: "Jeremiah" },
  { pattern: /\bYechezkel\b/g, replacement: "Ezekiel" },
  { pattern: /\bYechezkeil\b/g, replacement: "Ezekiel" },
  // Twelve Minor Prophets
  { pattern: /\bHoshea\b/g, replacement: "Hosea" },
  { pattern: /\bYoel\b/g, replacement: "Joel" },
  { pattern: /\bOvadiah\b/g, replacement: "Obadiah" },
  { pattern: /\bOvadya\b/g, replacement: "Obadiah" },
  { pattern: /\bYonah\b/g, replacement: "Jonah" },
  { pattern: /\bMicha\b/g, replacement: "Micah" },
  { pattern: /\bMichah\b/g, replacement: "Micah" },
  { pattern: /\bNachum\b/g, replacement: "Nahum" },
  { pattern: /\bChabakuk\b/g, replacement: "Habakkuk" },
  { pattern: /\bChavakuk\b/g, replacement: "Habakkuk" },
  { pattern: /\bTzefaniah\b/g, replacement: "Zephaniah" },
  { pattern: /\bTzfanya\b/g, replacement: "Zephaniah" },
  { pattern: /\bChaggai\b/g, replacement: "Haggai" },
  { pattern: /\bChagai\b/g, replacement: "Haggai" },
  { pattern: /\bZecharya\b/g, replacement: "Zechariah" },
  { pattern: /\bZecharia\b/g, replacement: "Zechariah" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 10 — TANAKH: KETUVIM (Writings)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bTehillim\b/g, replacement: "Psalms" },
  { pattern: /\bTehilim\b/g, replacement: "Psalms" },
  { pattern: /\bMishlei\b/g, replacement: "Proverbs" },
  { pattern: /\bKoheles\b/g, replacement: "Ecclesiastes" },
  { pattern: /\bKohelet\b/g, replacement: "Ecclesiastes" },
  { pattern: /\bQohelet\b/g, replacement: "Ecclesiastes" },
  { pattern: /\bIyov\b/g, replacement: "Job" },
  { pattern: /\bIyob\b/g, replacement: "Job" },
  { pattern: /\bShir\s+HaShirim\b/g, replacement: "Song of Songs" },
  { pattern: /\bShir\s+Hashirim\b/g, replacement: "Song of Songs" },
  { pattern: /\bRus\b/g, replacement: "Ruth" },
  { pattern: /\bEichah\b/g, replacement: "Lamentations" },
  { pattern: /\bEikhah\b/g, replacement: "Lamentations" },
  { pattern: /\bEicha\b/g, replacement: "Lamentations" },
  { pattern: /\bNechemya\b/g, replacement: "Nehemiah" },
  { pattern: /\bNechemia\b/g, replacement: "Nehemiah" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 11 — TALMUD TRACTATE ALTERNATE SPELLINGS
  // Ashkenazi/Yiddish pronunciations that differ enough to confuse the API.
  // ════════════════════════════════════════════════════════════════════════════
  // Berakhot
  { pattern: /\bBerachos\b/gi, replacement: "Berakhot" },
  { pattern: /\bBerachot\b/gi, replacement: "Berakhot" },
  { pattern: /\bBrachos\b/gi, replacement: "Berakhot" },
  { pattern: /\bBrachot\b/gi, replacement: "Berakhot" },
  // Shabbat
  { pattern: /\bShabbos\b/gi, replacement: "Shabbat" },
  // Eruvin/Eiruvin
  { pattern: /\bEruvin\b/gi, replacement: "Eiruvin" },
  // Pesachim
  { pattern: /\bPsachim\b/gi, replacement: "Pesachim" },
  // Yoma
  { pattern: /\bYuma\b/gi, replacement: "Yoma" },
  // Sukkah
  { pattern: /\bSukka\b/gi, replacement: "Sukkah" },
  // Beitzah
  { pattern: /\bBeisa\b/gi, replacement: "Beitzah" },
  { pattern: /\bBeiza\b/gi, replacement: "Beitzah" },
  { pattern: /\bBeizah\b/gi, replacement: "Beitzah" },
  // Ta'anit
  { pattern: /\bTaanis\b/gi, replacement: "Ta'anit" },
  { pattern: /\bTaanit\b/gi, replacement: "Ta'anit" },
  { pattern: /\bTa'anis\b/gi, replacement: "Ta'anit" },
  { pattern: /\bTaaniyos\b/gi, replacement: "Ta'anit" },
  // Megillah
  { pattern: /\bMegila\b/gi, replacement: "Megillah" },
  // Chagigah
  { pattern: /\bChagiga\b/gi, replacement: "Chagigah" },
  { pattern: /\bHagigah\b/gi, replacement: "Chagigah" },
  { pattern: /\bChagigos\b/gi, replacement: "Chagigah" },
  // Yevamot
  { pattern: /\bYevamos\b/gi, replacement: "Yevamot" },
  { pattern: /\bYevamoth\b/gi, replacement: "Yevamot" },
  // Ketubot
  { pattern: /\bKesuvos\b/gi, replacement: "Ketubot" },
  { pattern: /\bKesubos\b/gi, replacement: "Ketubot" },
  { pattern: /\bKetubos\b/gi, replacement: "Ketubot" },
  // Sotah
  { pattern: /\bSoto\b/gi, replacement: "Sotah" },
  // Gittin
  { pattern: /\bGitin\b/gi, replacement: "Gittin" },
  // Kiddushin
  { pattern: /\bKidushin\b/gi, replacement: "Kiddushin" },
  { pattern: /\bKidushim\b/gi, replacement: "Kiddushin" },
  // Sanhedrin
  { pattern: /\bSanhedrim\b/gi, replacement: "Sanhedrin" },
  // Makkot
  { pattern: /\bMakkos\b/gi, replacement: "Makkot" },
  { pattern: /\bMakos\b/gi, replacement: "Makkot" },
  // Shevuot
  { pattern: /\bShevuos\b/gi, replacement: "Shevuot" },
  { pattern: /\bShvuos\b/gi, replacement: "Shevuot" },
  { pattern: /\bShvuot\b/gi, replacement: "Shevuot" },
  // Horayot
  { pattern: /\bHorayos\b/gi, replacement: "Horayot" },
  { pattern: /\bHoriyot\b/gi, replacement: "Horayot" },
  // Zevachim
  { pattern: /\bZevahim\b/gi, replacement: "Zevachim" },
  // Menachot
  { pattern: /\bMenachos\b/gi, replacement: "Menachot" },
  { pattern: /\bMenahos\b/gi, replacement: "Menachot" },
  { pattern: /\bMenahot\b/gi, replacement: "Menachot" },
  // Chullin / Hullin
  { pattern: /\bChullin\b/gi, replacement: "Hullin" },
  { pattern: /\bChulin\b/gi, replacement: "Hullin" },
  // Bekhorot
  { pattern: /\bBechorot\b/gi, replacement: "Bekhorot" },
  { pattern: /\bBechoros\b/gi, replacement: "Bekhorot" },
  { pattern: /\bBekoros\b/gi, replacement: "Bekhorot" },
  // Arakhin
  { pattern: /\bArachin\b/gi, replacement: "Arakhin" },
  { pattern: /\bArcin\b/gi, replacement: "Arakhin" },
  // Keritot
  { pattern: /\bKerisus\b/gi, replacement: "Keritot" },
  { pattern: /\bKerisos\b/gi, replacement: "Keritot" },
  // Me'ilah
  { pattern: /\bMeilah\b/gi, replacement: "Me'ilah" },
  // Niddah
  { pattern: /\bNidah\b/gi, replacement: "Niddah" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 12 — MISHNAH TRACTATES (Pirkei Avot alternate spellings)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bPirkei\s+Avos\b/g, replacement: "Pirkei Avot" },
  { pattern: /\bPirke\s+Avot\b/g, replacement: "Pirkei Avot" },
  { pattern: /\bPirke\s+Avos\b/g, replacement: "Pirkei Avot" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 13 — MIDRASH RABBAH (Hebrew/Ashkenazi names → Sefaria canonical)
  // More specific compound names first.
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bBereishis\s+Rabbah\b/g, replacement: "Bereishit Rabbah" },
  { pattern: /\bShemos\s+Rabbah\b/g, replacement: "Shemot Rabbah" },
  { pattern: /\bDevorim\s+Rabbah\b/g, replacement: "Devarim Rabbah" },
  { pattern: /\bShir\s+HaShirim\s+Rabbah\b/g, replacement: "Shir Hashirim Rabbah" },
  { pattern: /\bEichah\s+Rabbah\b/g, replacement: "Eikhah Rabbah" },
  { pattern: /\bEicha\s+Rabbah\b/g, replacement: "Eikhah Rabbah" },
  { pattern: /\bKoheles\s+Rabbah\b/g, replacement: "Kohelet Rabbah" },
  { pattern: /\bRus\s+Rabbah\b/g, replacement: "Ruth Rabbah" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 7 — SHULCHAN ARUKH SECTION SHORTHANDS (standalone, no siman)
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: new RegExp(`\\bY${DP}D\\b`, "g"), replacement: "Yoreh Deah" },
  { pattern: new RegExp(`\\bO${DP}C\\b`, "g"), replacement: "Orach Chaim" },
  { pattern: new RegExp(`\\bE${DP}H\\b`, "g"), replacement: "Even HaEzer" },
  { pattern: new RegExp(`\\bC${DP}M\\b`, "g"), replacement: "Choshen Mishpat" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 7b — PREPOSITION NORMALISATION ("in" / "on" / "al" → correct form)
  //
  // In halachic writing "Tur in Y"D 201" means the same as "Tur on Y"D 201".
  // We normalise the preposition so the API gets the expected citation format.
  //
  // Pattern: "[work] in/on/al [section/tractate]"
  // These fire AFTER section shorthands so the section is already expanded.
  // ════════════════════════════════════════════════════════════════════════════
  // ── Preposition / location-phrase normalisation ───────────────────────────
  // All of these mean "on [tractate/book]" in halachic citation context.
  // SA section shorthands get a comma (Sefaria canonical: "Tur, Yoreh De'ah").
  { pattern: new RegExp(`\\s+(?:in|on|al|at)\\s+(?=Y${DP}D)`, "g"), replacement: ", " },
  { pattern: new RegExp(`\\s+(?:in|on|al|at)\\s+(?=O${DP}C)`, "g"), replacement: ", " },
  { pattern: new RegExp(`\\s+(?:in|on|al|at)\\s+(?=E${DP}H)`, "g"), replacement: ", " },
  { pattern: new RegExp(`\\s+(?:in|on|al|at)\\s+(?=C${DP}M)`, "g"), replacement: ", " },
  // Strip verbose location phrases: "at the top of", "at the beginning of", etc.
  { pattern: /\s+at\s+the\s+(?:top|bottom|beginning|start|end|head)\s+of\s+/g, replacement: " on " },
  { pattern: /\s+(?:at\s+the\s+)?(?:beginning|start|end|top|bottom|head)\s+of\s+/g, replacement: " on " },
  // General: any of these prepositions before a word of ≥3 chars → "on"
  // Require ≥3 chars to avoid "in a", "at it", "on an" etc.
  { pattern: /\s+(?:in|at|al)\s+(?=\w{3})/g, replacement: " on " },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 14 — JERUSALEM TALMUD (YERUSHALMI)
  // "Yerushalmi" prefix → "Jerusalem Talmud" so API finds the right corpus.
  // Must come before tractate-name expansions so both fire in sequence.
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bYerushalmi\b/g, replacement: "Jerusalem Talmud" },
  { pattern: /\bTalmud\s+Yerushalmi\b/g, replacement: "Jerusalem Talmud" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 15 — MASECHES / MASECHTA PREFIX STRIPPING
  // These Hebrew/Aramaic prefixes have no meaning for Sefaria lookup.
  // ════════════════════════════════════════════════════════════════════════════
  { pattern: /\bMaseches\s+/g, replacement: "" },
  { pattern: /\bMasechta\s+/g, replacement: "" },
  { pattern: /\bMasekhet\s+/g, replacement: "" },
  { pattern: /\bMasekhta\s+/g, replacement: "" },
  { pattern: /\bMasechet\s+/g, replacement: "" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 16 — RISHON / COMMENTARY NAME NORMALISATION
  // Ashkenazi alternate spellings → Sefaria canonical names.
  // ════════════════════════════════════════════════════════════════════════════
  // Tosafot
  { pattern: /\bTosfos\b/gi, replacement: "Tosafot" },
  { pattern: /\bTosafos\b/gi, replacement: "Tosafot" },
  { pattern: /\bTosfot\b/gi, replacement: "Tosafot" },
  // Rashi (usually fine, but cover alternate)
  { pattern: /\bRaschi\b/g, replacement: "Rashi" },
  // Rashba (Rashbo is an alternate abbreviation used in some texts)
  { pattern: /\bRashbo\b/g, replacement: "Rashba" },
  // Ritva
  { pattern: /\bRitba\b/g, replacement: "Ritva" },
  // Ran (Rabbenu Nissim)
  { pattern: /\bR(?:abbenu|abbeynu)\s+Nissim\b/gi, replacement: "Ran" },
  // Rosh (Rabbenu Asher)
  { pattern: /\bRabbenu\s+Asher\b/gi, replacement: "Rosh" },
  // Nimukei Yosef
  { pattern: /\bNimukei\s+Yosef\b/g, replacement: "Nimukei Yosef" },
  { pattern: /\bNimuke[iy]\s+Yosef\b/g, replacement: "Nimukei Yosef" },
  // Mordechai (the rishon on Talmud)
  { pattern: /\bMordechai\b/g, replacement: "Mordechai" },
  // Meiri
  { pattern: /\bMeiry\b/g, replacement: "Meiri" },
  { pattern: /\bBeit\s+HaBechirah\b/g, replacement: "Meiri" },
  { pattern: /\bBeis\s+HaBechirah\b/g, replacement: "Meiri" },
  // Maggid Mishneh
  { pattern: /\bMaggid\s+Mishneh\b/g, replacement: "Maggid Mishneh" },
  { pattern: /\bMagid\s+Mishneh\b/g, replacement: "Maggid Mishneh" },
  // Kessef Mishneh (Sefaria uses double-s)
  { pattern: /\bKe[ss]+ef\s+Mishneh\b/g, replacement: "Kessef Mishneh" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 17 — ACHARONIM (later authorities)
  // ════════════════════════════════════════════════════════════════════════════
  // Mishnah Berurah (alternate spellings)
  { pattern: /\bMishna\s+Berura\b/g, replacement: "Mishnah Berurah" },
  { pattern: /\bMishnah\s+Berura\b/g, replacement: "Mishnah Berurah" },
  { pattern: /\bMishneh\s+Berura\b/g, replacement: "Mishnah Berurah" },
  { pattern: /\bM(?:ishna|ishnah|ishneh)\s+B(?:erura|erurah)\b/g, replacement: "Mishnah Berurah" },
  // Chatam Sofer (Chasam Sofer is Ashkenazi pronunciation)
  { pattern: /\bChasam\s+Sofer\b/g, replacement: "Chatam Sofer" },
  { pattern: /\bChatam\s+Sofer\b/g, replacement: "Chatam Sofer" },
  { pattern: /\bHatam\s+Sofer\b/g, replacement: "Chatam Sofer" },
  // Noda BiYehudah (alternate spellings)
  { pattern: /\bNoda\s+B[i']?[Yy]ehudah\b/g, replacement: "Noda BiYehudah" },
  { pattern: /\bNoda\s+B[i']?[Yy]ehuda\b/g, replacement: "Noda BiYehudah" },
  { pattern: /\bNoda\s+Biy?[Yy]ehudah\b/g, replacement: "Noda BiYehudah" },
  // Igrot Moshe (Responsa of Rav Moshe Feinstein)
  { pattern: /\bIgros\s+Moshe\b/g, replacement: "Igrot Moshe" },
  { pattern: /\bIgrot\s+Moshe\b/g, replacement: "Igrot Moshe" },
  { pattern: /\bIgeros\s+Moshe\b/g, replacement: "Igrot Moshe" },
  // Aruch HaShulchan
  { pattern: /\bAruch\s+HaShulchan\b/g, replacement: "Aruch HaShulchan" },
  { pattern: /\bArukh\s+HaShulchan\b/g, replacement: "Aruch HaShulchan" },
  { pattern: /\bAruch\s+Hashulchan\b/g, replacement: "Aruch HaShulchan" },
  // Kaf HaChayim / Kaf HaChaim
  { pattern: /\bKaf\s+HaChai[im]m?\b/g, replacement: "Kaf HaChayim" },
  { pattern: /\bKaf\s+Hachai[im]m?\b/g, replacement: "Kaf HaChayim" },
  // Magen Avraham (on Orach Chayim)
  { pattern: /\bMagen\s+Avraham\b/g, replacement: "Magen Avraham" },
  { pattern: /\bMagen\s+Avrohom\b/g, replacement: "Magen Avraham" },
  // Beur HaGra
  { pattern: /\bBeur\s+HaGra\b/g, replacement: "Beur HaGra" },
  { pattern: /\bBiur\s+HaGra\b/g, replacement: "Beur HaGra" },
  // Chayei Adam
  { pattern: /\bChayei\s+Adam\b/g, replacement: "Chayei Adam" },
  { pattern: /\bChayyei\s+Adam\b/g, replacement: "Chayei Adam" },
  // Kitzur Shulchan Arukh
  { pattern: /\bKitzur\s+Shulchan\s+Aruch\b/g, replacement: "Kitzur Shulchan Arukh" },
  { pattern: /\bKitzur\s+Shulchan\s+Arukh\b/g, replacement: "Kitzur Shulchan Arukh" },
  { pattern: /\bKitzur\s+S(?:hulchan|hulkan)\s+A(?:ruch|rukh)\b/g, replacement: "Kitzur Shulchan Arukh" },
  // ════════════════════════════════════════════════════════════════════════════
  // SECTION 18 — TANNAITIC / MIDRASHIC WORKS
  // ════════════════════════════════════════════════════════════════════════════
  // Mekhilta DeRabbi Yishmael (most common "Mechilta")
  { pattern: /\bMechilta\s+(?:D[e']?Rabbi\s+Yishmael|DeRabbi\s+Yishmael)\b/g, replacement: "Mekhilta DeRabbi Yishmael" },
  { pattern: /\bMekhilta\s+(?:D[e']?Rabbi\s+Yishmael|DeRabbi\s+Yishmael)\b/g, replacement: "Mekhilta DeRabbi Yishmael" },
  { pattern: /\bMechilta\s+(?:D[e']?Rabbi\s+Shimon|DeRabbi\s+Shimon)\b/g, replacement: "Mekhilta DeRabbi Shimon Ben Yochai" },
  { pattern: /\bMekhilta\s+(?:D[e']?Rabbi\s+Shimon|DeRabbi\s+Shimon)\b/g, replacement: "Mekhilta DeRabbi Shimon Ben Yochai" },
  // bare "Mechilta" defaults to the most common version (Yishmael)
  { pattern: /\bMechilta\b/g, replacement: "Mekhilta DeRabbi Yishmael" },
  { pattern: /\bMekhilta\b/g, replacement: "Mekhilta DeRabbi Yishmael" },
  // Sifra (on Leviticus)
  { pattern: /\bSifra\b/g, replacement: "Sifra" },
  { pattern: /\bTorat\s+Kohanim\b/g, replacement: "Sifra" },
  // Sifrei (on Bamidbar / Devarim — try to distinguish)
  { pattern: /\bSifrei\s+(?:on\s+)?(?:Bamidbar|Numbers|Bemidbar)\b/gi, replacement: "Sifrei Bamidbar" },
  { pattern: /\bSifrei\s+(?:on\s+)?(?:Devarim|Devorim|Deuteronomy)\b/gi, replacement: "Sifrei Devarim" },
  { pattern: /\bSifre\s+(?:on\s+)?(?:Bamidbar|Numbers|Bemidbar)\b/gi, replacement: "Sifrei Bamidbar" },
  { pattern: /\bSifre\s+(?:on\s+)?(?:Devarim|Devorim|Deuteronomy)\b/gi, replacement: "Sifrei Devarim" },
  // bare Sifre/Sifrei without qualifier — default to Sifrei Devarim (more commonly cited)
  { pattern: /\bSifre\b/g, replacement: "Sifrei Devarim" },
  // Midrash Tanchuma
  { pattern: /\bMidrash\s+Tanchuma\b/g, replacement: "Midrash Tanchuma" },
  { pattern: /\bTanchuma\b/g, replacement: "Midrash Tanchuma" },
  { pattern: /\bTankhuma\b/g, replacement: "Midrash Tanchuma" },
  // Pesikta DeRav Kahana
  { pattern: /\bPesikta\s+D[e']?Rav\s+Kahana\b/g, replacement: "Pesikta DeRav Kahana" },
  { pattern: /\bPesikta\s+de-?Rab\s+Kahana\b/gi, replacement: "Pesikta DeRav Kahana" },
  { pattern: /\bPesikta\s+Rabbati\b/g, replacement: "Pesikta Rabbati" },
  // Pirkei DeRabbi Eliezer
  { pattern: /\bPirkei\s+(?:de-?|D[e']?)Rabbi\s+Eliezer\b/gi, replacement: "Pirkei DeRabbi Eliezer" },
  { pattern: /\bPDRE\b/g, replacement: "Pirkei DeRabbi Eliezer" }
];
function expandShortforms(text, skipRanges = []) {
  const rawMatches = [];
  for (const entry of SHORTFORM_EXPANSIONS) {
    const re = new RegExp(entry.pattern.source, "gi");
    let m;
    while ((m = re.exec(text)) !== null) {
      const matchStart = m.index;
      const matchEnd = m.index + m[0].length;
      if (skipRanges.some(([s, e]) => matchStart < e && s < matchEnd))
        continue;
      const expanded = entry.replacement.replace(
        /\$(\d+)/g,
        (_, n) => {
          var _a;
          return (_a = m[parseInt(n, 10)]) != null ? _a : "";
        }
      );
      rawMatches.push({
        start: matchStart,
        end: matchEnd,
        origText: m[0],
        expandedText: expanded
      });
    }
  }
  rawMatches.sort((a, b) => a.start - b.start);
  const filtered = [];
  let lastEnd = 0;
  for (const r of rawMatches) {
    if (r.start >= lastEnd) {
      filtered.push(r);
      lastEnd = r.end;
    }
  }
  let expandedText = "";
  const substitutions = [];
  let origPos = 0;
  for (const match of filtered) {
    expandedText += text.slice(origPos, match.start);
    const expandedStart = expandedText.length;
    expandedText += match.expandedText;
    const expandedEnd = expandedText.length;
    substitutions.push({
      origStart: match.start,
      origEnd: match.end,
      expandedStart,
      expandedEnd,
      origText: match.origText
    });
    origPos = match.end;
  }
  expandedText += text.slice(origPos);
  return { expandedText, substitutions };
}
function expandPageRanges(text) {
  return text.replace(
    /\b(\d+)([ab]?)-(\d+)([ab]?)\b/g,
    (full, n1, s1, n2, s2) => {
      if (n2.length < n1.length) {
        const padded = n1.slice(0, n1.length - n2.length) + n2;
        return `${n1}${s1}-${padded}${s2}`;
      }
      return full;
    }
  );
}
function mapToOriginal(expandedStart, expandedEnd, substitutions, origText) {
  function deltaAt(pos) {
    let d2 = 0;
    for (const s of substitutions) {
      if (s.expandedEnd <= pos) {
        d2 += s.origEnd - s.origStart - (s.expandedEnd - s.expandedStart);
      }
    }
    return d2;
  }
  for (const sub of substitutions) {
    if (expandedStart >= sub.expandedStart && expandedStart < sub.expandedEnd) {
      if (expandedEnd <= sub.expandedEnd) {
        return { origStart: sub.origStart, origEnd: sub.origEnd, label: sub.origText };
      }
      const origStart2 = sub.origStart;
      const origEnd2 = expandedEnd + deltaAt(expandedEnd);
      const raw = origText.slice(origStart2, Math.max(origStart2, origEnd2));
      const trimmed = raw.replace(/\s*\([^)]*\)\s*$/, "");
      return {
        origStart: origStart2,
        origEnd: origStart2 + trimmed.length,
        label: trimmed
      };
    }
  }
  const d = deltaAt(expandedStart);
  const origStart = expandedStart + d;
  const origEnd = expandedEnd + d;
  return {
    origStart,
    origEnd,
    label: origText.slice(origStart, origEnd)
  };
}

// src/main.ts
var DEFAULT_SETTINGS = {
  autoRun: false,
  autoRunDelay: 1500,
  enableShortformExpansion: true
};
var CONTEXTUAL_RE = /\b(?:the\s+)?([A-Z][a-zA-Z]*(?:\s+[A-Z][a-zA-Z]*){0,4})\s+(?:there|ibid\.?|ad\s+loc\.?)\b/g;
var commentaryCache = /* @__PURE__ */ new Map();
async function resolveCommentaryUrl(commentatorRaw, baseRefUrl) {
  var _a;
  const name = commentatorRaw.trim().replace(/\s+/g, " ");
  const cacheKey = `${name}|||${baseRefUrl}`;
  if (commentaryCache.has(cacheKey))
    return commentaryCache.get(cacheKey);
  const baseRef = baseRefUrl.replace(/_/g, " ").replace(/\.(\d)/, " $1");
  const candidateRef = `${name} on ${baseRef}`;
  try {
    const resp = await fetch(
      `https://www.sefaria.org/api/texts/${encodeURIComponent(candidateRef)}?context=0&pad=0`
    );
    if (!resp.ok) {
      commentaryCache.set(cacheKey, null);
      return null;
    }
    const data = await resp.json();
    if (data.error || !data.ref) {
      commentaryCache.set(cacheKey, null);
      return null;
    }
    const url = (_a = data.url) != null ? _a : data.ref.replace(/\s/g, "_");
    commentaryCache.set(cacheKey, url);
    return url;
  } catch (e) {
    commentaryCache.set(cacheKey, null);
    return null;
  }
}
async function resolveContextualRefs(content, linkedRefs, existingRanges) {
  if (linkedRefs.length === 0)
    return { content, count: 0 };
  const sortedRefs = [...linkedRefs].sort((a, b) => a.origStart - b.origStart);
  const matches = [];
  CONTEXTUAL_RE.lastIndex = 0;
  let m;
  while ((m = CONTEXTUAL_RE.exec(content)) !== null) {
    if (existingRanges.some(([s, e]) => rangesOverlap(m.index, m.index + m[0].length, s, e)))
      continue;
    matches.push({ start: m.index, end: m.index + m[0].length, fullMatch: m[0], commentatorRaw: m[1] });
  }
  if (matches.length === 0)
    return { content, count: 0 };
  const resolved = await Promise.all(
    matches.map(async (match) => {
      let nearestRef = null;
      for (let i = sortedRefs.length - 1; i >= 0; i--) {
        if (sortedRefs[i].origEnd <= match.start) {
          nearestRef = sortedRefs[i];
          break;
        }
      }
      if (!nearestRef)
        return null;
      const url = await resolveCommentaryUrl(match.commentatorRaw, nearestRef.refUrl);
      return url ? { match, url } : null;
    })
  );
  let result = content;
  let count = 0;
  const toApply = resolved.filter((r) => r !== null).sort((a, b) => b.match.start - a.match.start);
  for (const { match, url } of toApply) {
    const fullUrl = `https://www.sefaria.org/${url}`;
    result = result.slice(0, match.start) + `[${match.fullMatch}](${fullUrl})` + result.slice(match.end);
    count++;
  }
  return { content: result, count };
}
function rangesOverlap(aStart, aEnd, bStart, bEnd) {
  return aStart < bEnd && bStart < aEnd;
}
function getProtectedRanges(content) {
  const ranges = [];
  let m;
  const mdRe = /\[([^\]]*)\]\([^)]*\)/g;
  while ((m = mdRe.exec(content)) !== null) {
    ranges.push([m.index, m.index + m[0].length]);
  }
  const wikiRe = /\[\[([^\]]*)\]\]/g;
  while ((m = wikiRe.exec(content)) !== null) {
    ranges.push([m.index, m.index + m[0].length]);
  }
  return ranges;
}
async function pollAsyncTask(taskId) {
  var _a;
  const maxAttempts = 30;
  for (let i = 0; i < maxAttempts; i++) {
    await new Promise((resolve) => setTimeout(resolve, 1e3));
    const resp = await fetch(`https://www.sefaria.org/api/async/${taskId}`);
    if (!resp.ok)
      throw new Error(`Polling failed with status ${resp.status}`);
    const data = await resp.json();
    if (data.state === "SUCCESS")
      return data;
    if (data.state === "FAILURE")
      throw new Error((_a = data.error) != null ? _a : "Task failed");
  }
  throw new Error("Timed out waiting for Sefaria response (30s)");
}
async function linkCitations(app, file, settings) {
  var _a;
  const content = await app.vault.read(file);
  const existingRanges = getProtectedRanges(content);
  const { expandedText: shortformExpanded, substitutions } = settings.enableShortformExpansion ? expandShortforms(content, existingRanges) : { expandedText: content, substitutions: [] };
  const expandedText = expandPageRanges(shortformExpanded);
  const submitResp = await fetch("https://www.sefaria.org/api/find-refs", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: { title: "", body: expandedText }, lang: "en" })
  });
  if (submitResp.status !== 202) {
    throw new Error(`Unexpected status from find-refs: ${submitResp.status}`);
  }
  const { task_id } = await submitResp.json();
  const taskResult = await pollAsyncTask(task_id);
  if (!taskResult.result)
    throw new Error("Task succeeded but returned no result");
  const { results, refData } = taskResult.result.body;
  const expandedProtectedRanges = getProtectedRanges(expandedText);
  const processedRefs = /* @__PURE__ */ new Set();
  const processedRanges = [];
  const linkedRefs = [];
  const sorted = (results != null ? results : []).sort((a, b) => b.startChar - a.startChar);
  let newContent = content;
  let linkedCount = 0;
  for (const result of sorted) {
    const ref = (_a = result.refs) == null ? void 0 : _a[0];
    if (!ref)
      continue;
    const refInfo = refData[ref];
    if (!(refInfo == null ? void 0 : refInfo.url))
      continue;
    if (processedRefs.has(ref))
      continue;
    if (expandedProtectedRanges.some(
      ([s, e]) => rangesOverlap(result.startChar, result.endChar, s, e)
    ))
      continue;
    const mapped = mapToOriginal(
      result.startChar,
      result.endChar,
      substitutions,
      content
    );
    if (existingRanges.some(([s, e]) => rangesOverlap(mapped.origStart, mapped.origEnd, s, e)))
      continue;
    if (processedRanges.some(([s, e]) => rangesOverlap(mapped.origStart, mapped.origEnd, s, e)))
      continue;
    let { origStart, origEnd, label } = mapped;
    if (result.text) {
      const window2 = content.slice(origStart, origEnd);
      const idx = window2.toLowerCase().indexOf(result.text.toLowerCase());
      if (idx !== -1 && idx + result.text.length <= window2.length) {
        origStart = origStart + idx;
        origEnd = origStart + result.text.length;
        label = content.slice(origStart, origEnd);
      }
    }
    const url = `https://www.sefaria.org/${refInfo.url}`;
    newContent = newContent.slice(0, origStart) + `[${label}](${url})` + newContent.slice(origEnd);
    processedRefs.add(ref);
    processedRanges.push([origStart, origEnd]);
    linkedRefs.push({ origStart, origEnd, ref, refUrl: refInfo.url });
    linkedCount++;
  }
  const updatedExistingRanges = getProtectedRanges(newContent);
  const { content: finalContent, count: contextualCount } = await resolveContextualRefs(
    newContent,
    linkedRefs,
    updatedExistingRanges
  );
  let outputContent = finalContent;
  const titleUrl = await resolveTitleUrl(file.basename, settings);
  if (titleUrl) {
    const fullTitleUrl = `https://www.sefaria.org/${titleUrl}`;
    const titleLine = `*[${file.basename}](${fullTitleUrl})*`;
    const firstLine = outputContent.split("\n")[0];
    const alreadyHasTitleLink = firstLine.startsWith("*[") && firstLine.includes("sefaria.org");
    if (!alreadyHasTitleLink) {
      outputContent = titleLine + "\n" + outputContent;
    }
  }
  const totalCount = linkedCount + contextualCount;
  if (totalCount === 0 && outputContent === finalContent) {
    new import_obsidian.Notice("No citations found");
    return;
  }
  await app.vault.modify(file, outputContent);
  new import_obsidian.Notice(`Linked ${totalCount} citation${totalCount === 1 ? "" : "s"}`);
}
async function resolveTitleUrl(title, settings) {
  var _a;
  const { expandedText } = settings.enableShortformExpansion ? expandShortforms(title, []) : { expandedText: title, substitutions: [] };
  const expanded = expandPageRanges(expandedText);
  try {
    const resp = await fetch(
      `https://www.sefaria.org/api/texts/${encodeURIComponent(expanded)}?context=0&pad=0`
    );
    if (!resp.ok)
      return null;
    const data = await resp.json();
    if (data.error || !data.ref)
      return null;
    return (_a = data.url) != null ? _a : data.ref.replace(/\s/g, "_");
  } catch (e) {
    return null;
  }
}
var SefariaLinkerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.autoRunTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("link", "Link Sefaria citations", async () => {
      const file = this.app.workspace.getActiveFile();
      if (!file) {
        new import_obsidian.Notice("No active file");
        return;
      }
      try {
        await linkCitations(this.app, file, this.settings);
      } catch (err) {
        new import_obsidian.Notice(`Sefaria Linker error: ${err.message}`);
      }
    });
    this.addCommand({
      id: "link-citations",
      name: "Link citations in current note",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("No active file");
          return;
        }
        try {
          await linkCitations(this.app, file, this.settings);
        } catch (err) {
          new import_obsidian.Notice(`Sefaria Linker error: ${err.message}`);
        }
      }
    });
    this.addCommand({
      id: "unlink-citations",
      name: "Unlink Sefaria citations in current note",
      callback: async () => {
        var _a;
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("No active file");
          return;
        }
        const content = await this.app.vault.read(file);
        const stripped = content.replace(
          /\[([^\]]+)\]\(https:\/\/www\.sefaria\.org\/[^)]+\)/g,
          "$1"
        );
        if (stripped === content) {
          new import_obsidian.Notice("No Sefaria links found");
          return;
        }
        const count = ((_a = content.match(/\[([^\]]+)\]\(https:\/\/www\.sefaria\.org\/[^)]+\)/g)) != null ? _a : []).length;
        await this.app.vault.modify(file, stripped);
        new import_obsidian.Notice(`Removed ${count} Sefaria link${count === 1 ? "" : "s"}`);
      }
    });
    this.addCommand({
      id: "toggle-auto-run",
      name: "Toggle auto-run",
      callback: async () => {
        this.settings.autoRun = !this.settings.autoRun;
        await this.saveSettings();
        new import_obsidian.Notice(`Sefaria auto-run ${this.settings.autoRun ? "enabled" : "disabled"}`);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!this.settings.autoRun || !file)
          return;
        if (this.autoRunTimer !== null)
          window.clearTimeout(this.autoRunTimer);
        this.autoRunTimer = window.setTimeout(async () => {
          this.autoRunTimer = null;
          try {
            await linkCitations(this.app, file, this.settings);
          } catch (err) {
            new import_obsidian.Notice(`Sefaria Linker error: ${err.message}`);
          }
        }, this.settings.autoRunDelay);
      })
    );
    this.addSettingTab(new SefariaLinkerSettingTab(this.app, this));
  }
  onunload() {
    if (this.autoRunTimer !== null)
      window.clearTimeout(this.autoRunTimer);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SefariaLinkerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sefaria Linker Settings" });
    new import_obsidian.Setting(containerEl).setName("Auto-run on file open").setDesc("Automatically detect and link citations when a note is opened.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRun).onChange(async (value) => {
        this.plugin.settings.autoRun = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-run delay (ms)").setDesc("How long to wait after opening a file before running (milliseconds).").addText(
      (text) => text.setPlaceholder("1500").setValue(String(this.plugin.settings.autoRunDelay)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 0) {
          this.plugin.settings.autoRunDelay = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Expand halachic shortforms before linking").setDesc(
      "Expand abbreviations like Shach 120.5, Taz, B\u2019\u2019H, Sh\u2019\u2019A, A\u2019\u2019Z etc. before sending to Sefaria, so they can be detected and linked. The original shortform text is preserved as the link label."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableShortformExpansion).onChange(async (value) => {
        this.plugin.settings.enableShortformExpansion = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
