/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SefariaLinkerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/expansions.ts
var DP = `(?:''|[""\u05F4])`;
var SHORTFORM_EXPANSIONS = [
  // ── Shulchan Arukh + section override (most specific first) ─────────────
  {
    // Sh''A O"C 123.4  →  Shulchan Arukh, Orach Chayim 123:4
    pattern: new RegExp(`\\bSh${DP}A\\s+O${DP}C\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Shulchan Arukh, Orach Chayim $1:$2"
  },
  {
    // Sh''A E"H 123.4  →  Shulchan Arukh, Even HaEzer 123:4
    pattern: new RegExp(`\\bSh${DP}A\\s+E${DP}H\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Shulchan Arukh, Even HaEzer $1:$2"
  },
  {
    // Sh''A C"M 123.4  →  Shulchan Arukh, Choshen Mishpat 123:4
    pattern: new RegExp(`\\bSh${DP}A\\s+C${DP}M\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Shulchan Arukh, Choshen Mishpat $1:$2"
  },
  {
    // Sh''A 123.4  (bare, defaults to Yoreh De'ah)
    pattern: new RegExp(`\\bSh${DP}A\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Shulchan Arukh, Yoreh De'ah $1:$2"
  },
  // ── Shulchan Arukh commentaries on Yoreh De'ah ──────────────────────────
  {
    pattern: /\bShach\s+(\d+)\.(\d+)/g,
    replacement: "Siftei Kohen on Shulchan Arukh, Yoreh De'ah $1:$2"
  },
  {
    pattern: /\bTaz\s+(\d+)\.(\d+)/g,
    replacement: "Turei Zahav on Shulchan Arukh, Yoreh De'ah $1:$2"
  },
  {
    // B''H  (Ba'er Hetev)
    pattern: new RegExp(`\\bB${DP}H\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Ba'er Hetev on Shulchan Arukh, Yoreh De'ah $1:$2"
  },
  {
    // N''HaK  (Nekudot HaKesef)
    pattern: new RegExp(`\\bN${DP}HaK\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Nekudot HaKesef on Shulchan Arukh, Yoreh De'ah $1:$2"
  },
  {
    // P''T  (Pischei Teshuva)
    pattern: new RegExp(`\\bP${DP}T\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Pischei Teshuva on Shulchan Arukh, Yoreh De'ah $1:$2"
  },
  {
    // B''Y  (Beit Yosef)
    pattern: new RegExp(`\\bB${DP}Y\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Beit Yosef, Yoreh De'ah $1:$2"
  },
  {
    // D''M  (Darkei Moshe)
    pattern: new RegExp(`\\bD${DP}M\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Darkei Moshe, Yoreh De'ah $1:$2"
  },
  // ── Tur ──────────────────────────────────────────────────────────────────
  {
    pattern: /\bTur\s+(\d+)\.(\d+)/g,
    replacement: "Tur, Yoreh De'ah $1:$2"
  },
  // ── Rambam / Mishneh Torah ────────────────────────────────────────────────
  {
    // M''A  (Mishneh Torah, Forbidden Foods)
    pattern: new RegExp(`\\bM${DP}A\\s+(\\d+)\\.(\\d+)`, "g"),
    replacement: "Mishneh Torah, Forbidden Foods $1:$2"
  },
  // ── Standalone Rishon works ───────────────────────────────────────────────
  {
    pattern: /\bIVHA\b/g,
    replacement: "Issur VeHeter HaArokh"
  },
  {
    pattern: /\bSmak\b/g,
    replacement: "Sefer Mitzvot Katan"
  },
  {
    pattern: /\bSmag\b/g,
    replacement: "Sefer Mitzvot Gadol"
  },
  // ── Tractate abbreviations ────────────────────────────────────────────────
  {
    // A''Z  →  Avodah Zarah
    pattern: new RegExp(`\\bA${DP}Z\\b`, "g"),
    replacement: "Avodah Zarah"
  },
  // Existing single-quote abbreviations already handled by the old expansion
  // are kept here so everything lives in one place:
  {
    pattern: new RegExp(`\\bB${DP}K\\b`, "g"),
    replacement: "Bava Kamma"
  },
  {
    pattern: new RegExp(`\\bB${DP}M\\b`, "g"),
    replacement: "Bava Metzia"
  },
  {
    pattern: new RegExp(`\\bB${DP}B\\b`, "g"),
    replacement: "Bava Batra"
  },
  {
    pattern: new RegExp(`\\bY${DP}T\\b`, "g"),
    replacement: "Beitza"
  },
  {
    pattern: new RegExp(`\\bR${DP}H\\b`, "g"),
    replacement: "Rosh Hashanah"
  },
  {
    pattern: new RegExp(`\\bM${DP}K\\b`, "g"),
    replacement: "Moed Katan"
  },
  // Shulchan Arukh section shorthands (standalone, no siman number)
  {
    pattern: new RegExp(`\\bY${DP}D\\b`, "g"),
    replacement: "Yoreh Deah"
  },
  {
    pattern: new RegExp(`\\bO${DP}C\\b`, "g"),
    replacement: "Orach Chaim"
  },
  {
    pattern: new RegExp(`\\bE${DP}H\\b`, "g"),
    replacement: "Even HaEzer"
  },
  {
    pattern: new RegExp(`\\bC${DP}M\\b`, "g"),
    replacement: "Choshen Mishpat"
  }
];
function expandShortforms(text, skipRanges = []) {
  const rawMatches = [];
  for (const entry of SHORTFORM_EXPANSIONS) {
    const re = new RegExp(entry.pattern.source, "g");
    let m;
    while ((m = re.exec(text)) !== null) {
      const matchStart = m.index;
      const matchEnd = m.index + m[0].length;
      if (skipRanges.some(([s, e]) => matchStart < e && s < matchEnd))
        continue;
      const expanded = entry.replacement.replace(
        /\$(\d+)/g,
        (_, n) => {
          var _a;
          return (_a = m[parseInt(n, 10)]) != null ? _a : "";
        }
      );
      rawMatches.push({
        start: matchStart,
        end: matchEnd,
        origText: m[0],
        expandedText: expanded
      });
    }
  }
  rawMatches.sort((a, b) => a.start - b.start);
  const filtered = [];
  let lastEnd = 0;
  for (const r of rawMatches) {
    if (r.start >= lastEnd) {
      filtered.push(r);
      lastEnd = r.end;
    }
  }
  let expandedText = "";
  const substitutions = [];
  let origPos = 0;
  for (const match of filtered) {
    expandedText += text.slice(origPos, match.start);
    const expandedStart = expandedText.length;
    expandedText += match.expandedText;
    const expandedEnd = expandedText.length;
    substitutions.push({
      origStart: match.start,
      origEnd: match.end,
      expandedStart,
      expandedEnd,
      origText: match.origText
    });
    origPos = match.end;
  }
  expandedText += text.slice(origPos);
  return { expandedText, substitutions };
}
function mapToOriginal(expandedStart, expandedEnd, substitutions, origText) {
  for (const sub of substitutions) {
    if (expandedStart >= sub.expandedStart && expandedEnd <= sub.expandedEnd) {
      return {
        origStart: sub.origStart,
        origEnd: sub.origEnd,
        label: sub.origText
      };
    }
  }
  let delta = 0;
  for (const sub of substitutions) {
    if (sub.expandedEnd <= expandedStart) {
      delta += sub.origEnd - sub.origStart - (sub.expandedEnd - sub.expandedStart);
    }
  }
  const origStart = expandedStart + delta;
  const origEnd = expandedEnd + delta;
  return {
    origStart,
    origEnd,
    label: origText.slice(origStart, origEnd)
  };
}

// src/main.ts
var DEFAULT_SETTINGS = {
  autoRun: true,
  autoRunDelay: 1500,
  enableShortformExpansion: true
};
var CONTEXTUAL_RE = /\b(?:the\s+)?([A-Z][a-zA-Z]*(?:\s+[A-Z][a-zA-Z]*){0,4})\s+(?:there|ibid\.?|ad\s+loc\.?)\b/g;
var commentaryCache = /* @__PURE__ */ new Map();
async function resolveCommentaryUrl(commentatorRaw, baseRefUrl) {
  var _a;
  const name = commentatorRaw.trim().replace(/\s+/g, " ");
  const cacheKey = `${name}|||${baseRefUrl}`;
  if (commentaryCache.has(cacheKey))
    return commentaryCache.get(cacheKey);
  const baseRef = baseRefUrl.replace(/_/g, " ").replace(/\.(\d)/, " $1");
  const candidateRef = `${name} on ${baseRef}`;
  try {
    const resp = await fetch(
      `https://www.sefaria.org/api/texts/${encodeURIComponent(candidateRef)}?context=0&pad=0`
    );
    if (!resp.ok) {
      commentaryCache.set(cacheKey, null);
      return null;
    }
    const data = await resp.json();
    if (data.error || !data.ref) {
      commentaryCache.set(cacheKey, null);
      return null;
    }
    const url = (_a = data.url) != null ? _a : data.ref.replace(/\s/g, "_");
    commentaryCache.set(cacheKey, url);
    return url;
  } catch (e) {
    commentaryCache.set(cacheKey, null);
    return null;
  }
}
async function resolveContextualRefs(content, linkedRefs, existingRanges) {
  if (linkedRefs.length === 0)
    return { content, count: 0 };
  const sortedRefs = [...linkedRefs].sort((a, b) => a.origStart - b.origStart);
  const matches = [];
  CONTEXTUAL_RE.lastIndex = 0;
  let m;
  while ((m = CONTEXTUAL_RE.exec(content)) !== null) {
    if (existingRanges.some(([s, e]) => rangesOverlap(m.index, m.index + m[0].length, s, e)))
      continue;
    matches.push({ start: m.index, end: m.index + m[0].length, fullMatch: m[0], commentatorRaw: m[1] });
  }
  if (matches.length === 0)
    return { content, count: 0 };
  const resolved = await Promise.all(
    matches.map(async (match) => {
      let nearestRef = null;
      for (let i = sortedRefs.length - 1; i >= 0; i--) {
        if (sortedRefs[i].origEnd <= match.start) {
          nearestRef = sortedRefs[i];
          break;
        }
      }
      if (!nearestRef)
        return null;
      const url = await resolveCommentaryUrl(match.commentatorRaw, nearestRef.refUrl);
      return url ? { match, url } : null;
    })
  );
  let result = content;
  let count = 0;
  const toApply = resolved.filter((r) => r !== null).sort((a, b) => b.match.start - a.match.start);
  for (const { match, url } of toApply) {
    const fullUrl = `https://www.sefaria.org/${url}`;
    result = result.slice(0, match.start) + `[${match.fullMatch}](${fullUrl})` + result.slice(match.end);
    count++;
  }
  return { content: result, count };
}
function rangesOverlap(aStart, aEnd, bStart, bEnd) {
  return aStart < bEnd && bStart < aEnd;
}
function getExistingSefariaLinkRanges(content) {
  const ranges = [];
  const re = /\[([^\]]+)\]\(https:\/\/www\.sefaria\.org\/[^)]+\)/g;
  let match;
  while ((match = re.exec(content)) !== null) {
    ranges.push([match.index, match.index + match[0].length]);
  }
  return ranges;
}
async function pollAsyncTask(taskId) {
  var _a;
  const maxAttempts = 30;
  for (let i = 0; i < maxAttempts; i++) {
    await new Promise((resolve) => setTimeout(resolve, 1e3));
    const resp = await fetch(`https://www.sefaria.org/api/async/${taskId}`);
    if (!resp.ok)
      throw new Error(`Polling failed with status ${resp.status}`);
    const data = await resp.json();
    if (data.state === "SUCCESS")
      return data;
    if (data.state === "FAILURE")
      throw new Error((_a = data.error) != null ? _a : "Task failed");
  }
  throw new Error("Timed out waiting for Sefaria response (30s)");
}
async function linkCitations(app, file, settings) {
  var _a;
  const content = await app.vault.read(file);
  const existingRanges = getExistingSefariaLinkRanges(content);
  const { expandedText, substitutions } = settings.enableShortformExpansion ? expandShortforms(content, existingRanges) : { expandedText: content, substitutions: [] };
  const submitResp = await fetch("https://www.sefaria.org/api/find-refs", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: { title: "", body: expandedText }, lang: "en" })
  });
  if (submitResp.status !== 202) {
    throw new Error(`Unexpected status from find-refs: ${submitResp.status}`);
  }
  const { task_id } = await submitResp.json();
  const taskResult = await pollAsyncTask(task_id);
  if (!taskResult.result)
    throw new Error("Task succeeded but returned no result");
  const { results, refData } = taskResult.result.body;
  const processedRefs = /* @__PURE__ */ new Set();
  const processedRanges = [];
  const linkedRefs = [];
  const sorted = (results != null ? results : []).sort((a, b) => b.startChar - a.startChar);
  let newContent = content;
  let linkedCount = 0;
  for (const result of sorted) {
    const ref = (_a = result.refs) == null ? void 0 : _a[0];
    if (!ref)
      continue;
    const refInfo = refData[ref];
    if (!(refInfo == null ? void 0 : refInfo.url))
      continue;
    if (processedRefs.has(ref))
      continue;
    const { origStart, origEnd, label } = mapToOriginal(
      result.startChar,
      result.endChar,
      substitutions,
      content
    );
    if (existingRanges.some(([s, e]) => rangesOverlap(origStart, origEnd, s, e)))
      continue;
    if (processedRanges.some(([s, e]) => rangesOverlap(origStart, origEnd, s, e)))
      continue;
    const url = `https://www.sefaria.org/${refInfo.url}`;
    newContent = newContent.slice(0, origStart) + `[${label}](${url})` + newContent.slice(origEnd);
    processedRefs.add(ref);
    processedRanges.push([origStart, origEnd]);
    linkedRefs.push({ origStart, origEnd, ref, refUrl: refInfo.url });
    linkedCount++;
  }
  const updatedExistingRanges = getExistingSefariaLinkRanges(newContent);
  const { content: finalContent, count: contextualCount } = await resolveContextualRefs(
    newContent,
    linkedRefs,
    updatedExistingRanges
  );
  const totalCount = linkedCount + contextualCount;
  if (totalCount === 0) {
    new import_obsidian.Notice("No citations found");
    return;
  }
  await app.vault.modify(file, finalContent);
  new import_obsidian.Notice(`Linked ${totalCount} citation${totalCount === 1 ? "" : "s"}`);
}
var SefariaLinkerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.autoRunTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "link-citations",
      name: "Link citations in current note",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("No active file");
          return;
        }
        try {
          await linkCitations(this.app, file, this.settings);
        } catch (err) {
          new import_obsidian.Notice(`Sefaria Linker error: ${err.message}`);
        }
      }
    });
    this.addCommand({
      id: "toggle-auto-run",
      name: "Toggle auto-run",
      callback: async () => {
        this.settings.autoRun = !this.settings.autoRun;
        await this.saveSettings();
        new import_obsidian.Notice(`Sefaria auto-run ${this.settings.autoRun ? "enabled" : "disabled"}`);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!this.settings.autoRun || !file)
          return;
        if (this.autoRunTimer !== null)
          window.clearTimeout(this.autoRunTimer);
        this.autoRunTimer = window.setTimeout(async () => {
          this.autoRunTimer = null;
          try {
            await linkCitations(this.app, file, this.settings);
          } catch (err) {
            new import_obsidian.Notice(`Sefaria Linker error: ${err.message}`);
          }
        }, this.settings.autoRunDelay);
      })
    );
    this.addSettingTab(new SefariaLinkerSettingTab(this.app, this));
  }
  onunload() {
    if (this.autoRunTimer !== null)
      window.clearTimeout(this.autoRunTimer);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SefariaLinkerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sefaria Linker Settings" });
    new import_obsidian.Setting(containerEl).setName("Auto-run on file open").setDesc("Automatically detect and link citations when a note is opened.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRun).onChange(async (value) => {
        this.plugin.settings.autoRun = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-run delay (ms)").setDesc("How long to wait after opening a file before running (milliseconds).").addText(
      (text) => text.setPlaceholder("1500").setValue(String(this.plugin.settings.autoRunDelay)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 0) {
          this.plugin.settings.autoRunDelay = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Expand halachic shortforms before linking").setDesc(
      "Expand abbreviations like Shach 120.5, Taz, B\u2019\u2019H, Sh\u2019\u2019A, A\u2019\u2019Z etc. before sending to Sefaria, so they can be detected and linked. The original shortform text is preserved as the link label."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableShortformExpansion).onChange(async (value) => {
        this.plugin.settings.enableShortformExpansion = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
