/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SefariaLinkerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  autoRun: true,
  autoRunDelay: 1500
};
function rangesOverlap(aStart, aEnd, bStart, bEnd) {
  return aStart < bEnd && bStart < aEnd;
}
function getExistingSefariaLinkRanges(content) {
  const ranges = [];
  const linkRegex = /\[([^\]]+)\]\(https:\/\/www\.sefaria\.org\/[^)]+\)/g;
  let match;
  while ((match = linkRegex.exec(content)) !== null) {
    ranges.push([match.index, match.index + match[0].length]);
  }
  return ranges;
}
async function pollAsyncTask(taskId) {
  var _a;
  const maxAttempts = 30;
  for (let i = 0; i < maxAttempts; i++) {
    await new Promise((resolve) => setTimeout(resolve, 1e3));
    const resp = await fetch(
      `https://www.sefaria.org/api/async/${taskId}`
    );
    if (!resp.ok) {
      throw new Error(`Polling failed with status ${resp.status}`);
    }
    const data = await resp.json();
    if (data.state === "SUCCESS") {
      return data;
    }
    if (data.state === "FAILURE") {
      throw new Error((_a = data.error) != null ? _a : "Task failed");
    }
  }
  throw new Error("Timed out waiting for Sefaria response (30s)");
}
async function linkCitations(app, file) {
  var _a;
  const content = await app.vault.read(file);
  const submitResp = await fetch("https://www.sefaria.org/api/find-refs", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      text: { title: "", body: content },
      lang: "he"
    })
  });
  if (submitResp.status !== 202) {
    throw new Error(`Unexpected status from find-refs: ${submitResp.status}`);
  }
  const { task_id } = await submitResp.json();
  const taskResult = await pollAsyncTask(task_id);
  if (!taskResult.result) {
    throw new Error("Task succeeded but returned no result");
  }
  const { results, refData } = taskResult.result.body;
  if (!results || results.length === 0) {
    new import_obsidian.Notice("No citations found");
    return;
  }
  const existingRanges = getExistingSefariaLinkRanges(content);
  const processedRefs = /* @__PURE__ */ new Set();
  const processedRanges = [];
  const sorted = [...results].sort((a, b) => b.startChar - a.startChar);
  let newContent = content;
  let linkedCount = 0;
  for (const result of sorted) {
    const ref = (_a = result.refs) == null ? void 0 : _a[0];
    if (!ref)
      continue;
    const refInfo = refData[ref];
    if (!(refInfo == null ? void 0 : refInfo.url))
      continue;
    if (processedRefs.has(ref))
      continue;
    const { startChar, endChar, text } = result;
    const overlapsExisting = existingRanges.some(
      ([s, e]) => rangesOverlap(startChar, endChar, s, e)
    );
    if (overlapsExisting)
      continue;
    const overlapsProcessed = processedRanges.some(
      ([s, e]) => rangesOverlap(startChar, endChar, s, e)
    );
    if (overlapsProcessed)
      continue;
    const url = `https://www.sefaria.org/${refInfo.url}`;
    const replacement = `[${text}](${url})`;
    newContent = newContent.slice(0, startChar) + replacement + newContent.slice(endChar);
    processedRefs.add(ref);
    processedRanges.push([startChar, endChar]);
    linkedCount++;
  }
  if (linkedCount === 0) {
    new import_obsidian.Notice("No citations found");
    return;
  }
  await app.vault.modify(file, newContent);
  new import_obsidian.Notice(`Linked ${linkedCount} citation${linkedCount === 1 ? "" : "s"}`);
}
var SefariaLinkerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.autoRunTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "link-citations",
      name: "Link citations in current note",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("No active file");
          return;
        }
        try {
          await linkCitations(this.app, file);
        } catch (err) {
          new import_obsidian.Notice(`Sefaria Linker error: ${err.message}`);
        }
      }
    });
    this.addCommand({
      id: "toggle-auto-run",
      name: "Toggle auto-run",
      callback: async () => {
        this.settings.autoRun = !this.settings.autoRun;
        await this.saveSettings();
        new import_obsidian.Notice(
          `Sefaria auto-run ${this.settings.autoRun ? "enabled" : "disabled"}`
        );
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!this.settings.autoRun || !file)
          return;
        if (this.autoRunTimer !== null) {
          window.clearTimeout(this.autoRunTimer);
        }
        this.autoRunTimer = window.setTimeout(async () => {
          this.autoRunTimer = null;
          try {
            await linkCitations(this.app, file);
          } catch (err) {
            new import_obsidian.Notice(
              `Sefaria Linker error: ${err.message}`
            );
          }
        }, this.settings.autoRunDelay);
      })
    );
    this.addSettingTab(new SefariaLinkerSettingTab(this.app, this));
  }
  onunload() {
    if (this.autoRunTimer !== null) {
      window.clearTimeout(this.autoRunTimer);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SefariaLinkerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sefaria Linker Settings" });
    new import_obsidian.Setting(containerEl).setName("Auto-run on file open").setDesc(
      "Automatically detect and link citations when a note is opened."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRun).onChange(async (value) => {
        this.plugin.settings.autoRun = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-run delay (ms)").setDesc(
      "How long to wait after opening a file before running (milliseconds)."
    ).addText(
      (text) => text.setPlaceholder("1500").setValue(String(this.plugin.settings.autoRunDelay)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 0) {
          this.plugin.settings.autoRunDelay = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};
